heat_template_version: 2013-05-23
description: >
  deploy web app

  parameters:
  
  key_name:
    type: string
    default: demo_heat_key
  
  instance_type:
    type: string
    default: t1.4core-4g-40g
    constraints:
      - allowed_values: [m1.sminy, m1.small, m1.medium, m1.large m1.xlarge, t1.2core-2g-40g, t1.4core-4g-40g]
  
  image_id:
    default: win2008srv-enterprise-v1.4.1
    type: string
    constraints:
      - allowed_values: [ win2012-srv-v0.1, win2008srv-enterprise-v1.4.1 ]
  
  app_name:
    default: UpthrustSkies.Web
    type: string
    description: >
      app project name
  
  app_url:
    default: http://10.14.40.45:8001/UploadFile/UpthrustSkies.rar
    type: string
    description: app project resources

resources:
  
  iis:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
        - network : public-ivt-direct-net
      user_data: |
          #ps1_sysnative
          Import-Module WebAdministration
          $ErrorActionPreference = 'Stop'
          #eventlog
          New-EventLog -LogName AppDeploylog -Source openstack_heat, JobDone, Remark
          function ExecRetry($command, $maxRetryCount = 10, $retryInterval=2)
          {
              $currErrorActionPreference = $ErrorActionPreference
              $ErrorActionPreference = "Continue"
              $retryCount = 0
              while ($true)
              {
                  try
                  {
                      & $command
                      break
                  }
                  catch [System.Exception]
                  {
                      $retryCount++
                      if ($retryCount -ge $maxRetryCount)
                      {
                          $ErrorActionPreference = $currErrorActionPreference
                          throw
                      }
                      else
                      {
                          Write-EventLog -LogName AppDeploylog -Source openstack_heat -EntryType Information -EventId 1 -Message $_.Exception
                          Start-Sleep $retryInterval
                      }
                  }
              }
              $ErrorActionPreference = $currErrorActionPreference
          }
          #set web root path
          ExecRetry {
            New-Item c:\wwwroot -type directory
          }
          #place project
          $projectname = "UpthrustSkies.Web"
          ExecRetry {
            $projectdir = "$ENV:Temp\$projectname.rar"
            $projecturl = "http://10.14.40.45:8002/UploadFile/UpThrustSkies.Web.rar"
            (new-object System.Net.WebClient).DownloadFile($projecturl, $projectdir)
            $zippath = "C:\Program Files\7-Zip\7z.exe"
            & $zippath x $projectdir -oC:\wwwroot -y -aos
            del $projectdir
          }
          #enable .netframework x64 iaspi&cgi
          ExecRetry {
            $frameworkPath = "$env:windir\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll"
            Set-WebConfiguration "/system.webServer/security/isapiCgiRestriction/add[@path='$frameworkPath']/@allowed" -value 'True' -PSPath:IIS:\
          }
          #new web item
          ExecRetry {
            New-Item iis:\Sites\$projectname -bindings @{protocol="http";bindingInformation="*:1001:"} -physicalPath C:\wwwroot
            New-Item iis:\AppPools\$projectname
            Set-ItemProperty iis:\AppPools\$projectname managedRuntimeVersion v4.0 
            Set-ItemProperty iis:\AppPools\$projectname ManagedPipelineMode 1
            New-Item IIS:\Sites\$projectname\$projectname -type Application -physicalpath C:\wwwroot\$projectname
            Set-ItemProperty IIS:\Sites\$projectname -name applicationPool -value $projectname
            Set-ItemProperty IIS:\Sites\$projectname\$projectname -name applicationPool -value $projectname
            Set-Location IIS:
            Start-WebSite -name "$projectname"
          }