heat_template_version: 2013-05-23
description: >
  deploy web app

parameters:  
  key_name:
    type: string
    default: demo_heat_key
  
  instance_type:
    type: string
    default: t1.4core-4g-40g
    constraints:
      - allowed_values: [m1.sminy, m1.small, m1.medium, m1.large m1.xlarge, t1.2core-2g-40g, t1.4core-4g-40g]
  
  image_id:
    default: win2008srv-enterprise-v1.4.1
    type: string
    constraints:
      - allowed_values: [ win2012-srv-v0.1, win2008srv-enterprise-v1.4.1 ]
  
  app_name:
    default: UpthrustSkies.Web
    type: string
    description: >
      app project name
  
  app_url:
    default: http://10.14.40.45:8002/UploadFile/UpthrustSkies.Web.rar
    type: string
    description: app project resources

  app_port:
    default: 1001
    type: string
    description: app port

resources:
  iis:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
        - network : public-ivt-direct-net
      user_data:
        str_replace:
          template: { get_file: iisweb.ps1}
          params:
            projectname: {get_param: app_name}
            appurl: {get_param: app_url}
            appport: {get_param: app_port}
